function ChannelOrder=bb_chanord(ChannelLabels)
% Sort EEG channels
% This function uses a Cell Array of EEG Labels and sorts them based on
% their location on a fronto-occipital gradient to create channel x 
% amplitude plots. Channels are labeled based on a 10-20 32 channel EEG 
% system naming scheme. 
% Author: Bahne H Bahners, BWH 2024 

channlabels=ChannelLabels;

ChannelOrder=[sort(find(contains(string(char(channlabels)),'Fp')));...
    find(contains(string(char(channlabels)),'AF'));...
    find(contains(string(char(channlabels)),'F')&...
    ~contains(string(char(channlabels)),'A')&...
    ~contains(string(char(channlabels)),'Fp')&...
    ~contains(string(char(channlabels)),'FC'));...
    find(contains(string(char(channlabels)),'FC'));...
    find(contains(string(char(channlabels)),'C')&...
    ~contains(string(char(channlabels)),'F')&...
    ~contains(string(char(channlabels)),'P'));...
    find(contains(string(char(channlabels)),'CP'));...
    find(contains(string(char(channlabels)),'P')&...
    ~contains(string(char(channlabels)),'C'));...
    find(contains(string(char(channlabels)),'T')&...
    ~contains(string(char(channlabels)),'P'));...
    find(contains(string(char(channlabels)),'O')&...
    ~contains(string(char(channlabels)),'P'))];

end
